spring:
    profile: test
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/downloader
        username: root
        password: root
        platform: mysql
    jpa:
        hibernate.ddl-auto: update
        generate-ddl: true
        show-sql: true

logging:
    level:
        root: INFO
